package com.ipn.mx.model.entities;
// Generated 2/11/2016 11:30:40 PM by Hibernate Tools 4.3.1



/**
 * Calificaciones generated by hbm2java
 */
public class Calificaciones  implements java.io.Serializable {


     private Integer idCalificaciones;
     private Examen examen;
     private Usuario usuario;
     private Double puntaje;

    public Calificaciones() {
    }

	
    public Calificaciones(Examen examen, Usuario usuario) {
        this.examen = examen;
        this.usuario = usuario;
    }
    public Calificaciones(Examen examen, Usuario usuario, Double puntaje) {
       this.examen = examen;
       this.usuario = usuario;
       this.puntaje = puntaje;
    }
   
    public Integer getIdCalificaciones() {
        return this.idCalificaciones;
    }
    
    public void setIdCalificaciones(Integer idCalificaciones) {
        this.idCalificaciones = idCalificaciones;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Double getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(Double puntaje) {
        this.puntaje = puntaje;
    }




}


