package com.ipn.mx.model.entities;
// Generated 1/11/2016 06:13:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private int idCarrera;
     private Centrodetrabajo centrodetrabajo;
     private String nombreCarrera;
     private Integer duracion;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Carrera() {
    }

	
    public Carrera(int idCarrera, Centrodetrabajo centrodetrabajo) {
        this.idCarrera = idCarrera;
        this.centrodetrabajo = centrodetrabajo;
    }
    public Carrera(int idCarrera, Centrodetrabajo centrodetrabajo, String nombreCarrera, Integer duracion, Set<Usuario> usuarios) {
       this.idCarrera = idCarrera;
       this.centrodetrabajo = centrodetrabajo;
       this.nombreCarrera = nombreCarrera;
       this.duracion = duracion;
       this.usuarios = usuarios;
    }
   
    public int getIdCarrera() {
        return this.idCarrera;
    }
    
    public void setIdCarrera(int idCarrera) {
        this.idCarrera = idCarrera;
    }
    public Centrodetrabajo getCentrodetrabajo() {
        return this.centrodetrabajo;
    }
    
    public void setCentrodetrabajo(Centrodetrabajo centrodetrabajo) {
        this.centrodetrabajo = centrodetrabajo;
    }
    public String getNombreCarrera() {
        return this.nombreCarrera;
    }
    
    public void setNombreCarrera(String nombreCarrera) {
        this.nombreCarrera = nombreCarrera;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


