package com.ipn.mx.model.entities;
// Generated 1/11/2016 06:13:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Centrodetrabajo generated by hbm2java
 */
public class Centrodetrabajo  implements java.io.Serializable {


     private int idcentrodetrabajo;
     private String nombreCentroDeTrabajo;
     private Set<Carrera> carreras = new HashSet<Carrera>(0);

    public Centrodetrabajo() {
    }

	
    public Centrodetrabajo(int idcentrodetrabajo) {
        this.idcentrodetrabajo = idcentrodetrabajo;
    }
    public Centrodetrabajo(int idcentrodetrabajo, String nombreCentroDeTrabajo, Set<Carrera> carreras) {
       this.idcentrodetrabajo = idcentrodetrabajo;
       this.nombreCentroDeTrabajo = nombreCentroDeTrabajo;
       this.carreras = carreras;
    }
   
    public int getIdcentrodetrabajo() {
        return this.idcentrodetrabajo;
    }
    
    public void setIdcentrodetrabajo(int idcentrodetrabajo) {
        this.idcentrodetrabajo = idcentrodetrabajo;
    }
    public String getNombreCentroDeTrabajo() {
        return this.nombreCentroDeTrabajo;
    }
    
    public void setNombreCentroDeTrabajo(String nombreCentroDeTrabajo) {
        this.nombreCentroDeTrabajo = nombreCentroDeTrabajo;
    }
    public Set<Carrera> getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Set<Carrera> carreras) {
        this.carreras = carreras;
    }




}


