package com.ipn.mx.model.entities;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private Integer idExamen;
     private Materias materias;
     private Date fechaActualizacion;
     private Date fechaRealizacion;
     private String titulo;
     private Set<Calificaciones> calificacioneses = new HashSet<Calificaciones>(0);
     private Set<Preguntas> preguntases = new HashSet<Preguntas>(0);

    public Examen() {
    }

	
    public Examen(Materias materias, String titulo) {
        this.materias = materias;
        this.titulo = titulo;
    }
    public Examen(Materias materias, Date fechaActualizacion, Date fechaRealizacion, String titulo, Set<Calificaciones> calificacioneses, Set<Preguntas> preguntases) {
       this.materias = materias;
       this.fechaActualizacion = fechaActualizacion;
       this.fechaRealizacion = fechaRealizacion;
       this.titulo = titulo;
       this.calificacioneses = calificacioneses;
       this.preguntases = preguntases;
    }
   
    public Integer getIdExamen() {
        return this.idExamen;
    }
    
    public void setIdExamen(Integer idExamen) {
        this.idExamen = idExamen;
    }
    public Materias getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Materias materias) {
        this.materias = materias;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Date getFechaRealizacion() {
        return this.fechaRealizacion;
    }
    
    public void setFechaRealizacion(Date fechaRealizacion) {
        this.fechaRealizacion = fechaRealizacion;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Set<Calificaciones> getCalificacioneses() {
        return this.calificacioneses;
    }
    
    public void setCalificacioneses(Set<Calificaciones> calificacioneses) {
        this.calificacioneses = calificacioneses;
    }
    public Set<Preguntas> getPreguntases() {
        return this.preguntases;
    }
    
    public void setPreguntases(Set<Preguntas> preguntases) {
        this.preguntases = preguntases;
    }




}


