package com.ipn.mx.model.entities;
// Generated 1/11/2016 06:13:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private int idExamen;
     private Materias materias;
     private Date fecha;
     private Set<Calificaciones> calificacioneses = new HashSet<Calificaciones>(0);
     private Set<Preguntas> preguntases = new HashSet<Preguntas>(0);

    public Examen() {
    }

	
    public Examen(int idExamen, Materias materias) {
        this.idExamen = idExamen;
        this.materias = materias;
    }
    public Examen(int idExamen, Materias materias, Date fecha, Set<Calificaciones> calificacioneses, Set<Preguntas> preguntases) {
       this.idExamen = idExamen;
       this.materias = materias;
       this.fecha = fecha;
       this.calificacioneses = calificacioneses;
       this.preguntases = preguntases;
    }
   
    public int getIdExamen() {
        return this.idExamen;
    }
    
    public void setIdExamen(int idExamen) {
        this.idExamen = idExamen;
    }
    public Materias getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Materias materias) {
        this.materias = materias;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<Calificaciones> getCalificacioneses() {
        return this.calificacioneses;
    }
    
    public void setCalificacioneses(Set<Calificaciones> calificacioneses) {
        this.calificacioneses = calificacioneses;
    }
    public Set<Preguntas> getPreguntases() {
        return this.preguntases;
    }
    
    public void setPreguntases(Set<Preguntas> preguntases) {
        this.preguntases = preguntases;
    }




}


