package com.ipn.mx.model.entities;
// Generated 1/11/2016 06:37:57 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Materias generated by hbm2java
 */
public class Materias  implements java.io.Serializable {


     private Integer idMaterias;
     private Roles roles;
     private String nombreMateria;
     private Integer creditos;
     private Set examens = new HashSet(0);

    public Materias() {
    }

	
    public Materias(Roles roles) {
        this.roles = roles;
    }
    public Materias(Roles roles, String nombreMateria, Integer creditos, Set examens) {
       this.roles = roles;
       this.nombreMateria = nombreMateria;
       this.creditos = creditos;
       this.examens = examens;
    }
   
    public Integer getIdMaterias() {
        return this.idMaterias;
    }
    
    public void setIdMaterias(Integer idMaterias) {
        this.idMaterias = idMaterias;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getNombreMateria() {
        return this.nombreMateria;
    }
    
    public void setNombreMateria(String nombreMateria) {
        this.nombreMateria = nombreMateria;
    }
    public Integer getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Integer creditos) {
        this.creditos = creditos;
    }
    public Set getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set examens) {
        this.examens = examens;
    }

}


