package com.ipn.mx.model.entities;
// Generated 1/11/2016 06:13:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materias generated by hbm2java
 */
public class Materias  implements java.io.Serializable {


     private int idMaterias;
     private Roles roles;
     private String nombreMateria;
     private Integer creditos;
     private Set<Examen> examens = new HashSet<Examen>(0);

    public Materias() {
    }

	
    public Materias(int idMaterias, Roles roles) {
        this.idMaterias = idMaterias;
        this.roles = roles;
    }
    public Materias(int idMaterias, Roles roles, String nombreMateria, Integer creditos, Set<Examen> examens) {
       this.idMaterias = idMaterias;
       this.roles = roles;
       this.nombreMateria = nombreMateria;
       this.creditos = creditos;
       this.examens = examens;
    }
   
    public int getIdMaterias() {
        return this.idMaterias;
    }
    
    public void setIdMaterias(int idMaterias) {
        this.idMaterias = idMaterias;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getNombreMateria() {
        return this.nombreMateria;
    }
    
    public void setNombreMateria(String nombreMateria) {
        this.nombreMateria = nombreMateria;
    }
    public Integer getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Integer creditos) {
        this.creditos = creditos;
    }
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }




}


