package com.ipn.mx.model.entities;
// Generated 4/11/2016 12:42:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materias generated by hbm2java
 */
public class Materias  implements java.io.Serializable {


     private Integer idMaterias;
     private String nombreMateria;
     private Integer creditos;
     private Set usuarios = new HashSet(0);
     private Set examens = new HashSet(0);

    public Materias() {
    }

    public Materias(String nombreMateria, Integer creditos, Set usuarios, Set examens) {
       this.nombreMateria = nombreMateria;
       this.creditos = creditos;
       this.usuarios = usuarios;
       this.examens = examens;
    }
   
    public Integer getIdMaterias() {
        return this.idMaterias;
    }
    
    public void setIdMaterias(Integer idMaterias) {
        this.idMaterias = idMaterias;
    }
    public String getNombreMateria() {
        return this.nombreMateria;
    }
    
    public void setNombreMateria(String nombreMateria) {
        this.nombreMateria = nombreMateria;
    }
    public Integer getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Integer creditos) {
        this.creditos = creditos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set examens) {
        this.examens = examens;
    }




}


