package com.ipn.mx.model.entities;
// Generated 8/11/2016 12:07:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Preguntas generated by hbm2java
 */
public class Preguntas  implements java.io.Serializable {


     private Integer idPregunta;
     private Examen examen;
     private String pregunta;
     private Integer estadoPregunta;
     private Set<Respuestas> respuestases = new HashSet<Respuestas>(0);

    public Preguntas() {
    }

	
    public Preguntas(Examen examen) {
        this.examen = examen;
    }
    public Preguntas(Examen examen, String pregunta, Integer estadoPregunta, Set<Respuestas> respuestases) {
       this.examen = examen;
       this.pregunta = pregunta;
       this.estadoPregunta = estadoPregunta;
       this.respuestases = respuestases;
    }
   
    public Integer getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(Integer idPregunta) {
        this.idPregunta = idPregunta;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public Integer getEstadoPregunta() {
        return this.estadoPregunta;
    }
    
    public void setEstadoPregunta(Integer estadoPregunta) {
        this.estadoPregunta = estadoPregunta;
    }
    public Set<Respuestas> getRespuestases() {
        return this.respuestases;
    }
    
    public void setRespuestases(Set<Respuestas> respuestases) {
        this.respuestases = respuestases;
    }




}


