package com.ipn.mx.model.entities;
// Generated 1/11/2016 06:13:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Preguntas generated by hbm2java
 */
public class Preguntas  implements java.io.Serializable {


     private int idPregunta;
     private Examen examen;
     private String pregunta;
     private Set<Respuestas> respuestases = new HashSet<Respuestas>(0);

    public Preguntas() {
    }

	
    public Preguntas(int idPregunta, Examen examen) {
        this.idPregunta = idPregunta;
        this.examen = examen;
    }
    public Preguntas(int idPregunta, Examen examen, String pregunta, Set<Respuestas> respuestases) {
       this.idPregunta = idPregunta;
       this.examen = examen;
       this.pregunta = pregunta;
       this.respuestases = respuestases;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public Set<Respuestas> getRespuestases() {
        return this.respuestases;
    }
    
    public void setRespuestases(Set<Respuestas> respuestases) {
        this.respuestases = respuestases;
    }




}


