package com.ipn.mx.model.entities;
// Generated 1/11/2016 06:13:01 PM by Hibernate Tools 4.3.1



/**
 * Respuestas generated by hbm2java
 */
public class Respuestas  implements java.io.Serializable {


     private int idRespuesta;
     private Preguntas preguntas;
     private String respuesta;

    public Respuestas() {
    }

	
    public Respuestas(int idRespuesta, Preguntas preguntas) {
        this.idRespuesta = idRespuesta;
        this.preguntas = preguntas;
    }
    public Respuestas(int idRespuesta, Preguntas preguntas, String respuesta) {
       this.idRespuesta = idRespuesta;
       this.preguntas = preguntas;
       this.respuesta = respuesta;
    }
   
    public int getIdRespuesta() {
        return this.idRespuesta;
    }
    
    public void setIdRespuesta(int idRespuesta) {
        this.idRespuesta = idRespuesta;
    }
    public Preguntas getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Preguntas preguntas) {
        this.preguntas = preguntas;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }




}


