package com.ipn.mx.model.entities;
// Generated 13/12/2016 12:01:18 PM by Hibernate Tools 4.3.1



/**
 * Respuestas generated by hbm2java
 */
public class Respuestas  implements java.io.Serializable {


     private Integer idRespuesta;
     private Preguntas preguntas;
     private String respuesta;
     private String respuestaExamen;

    public Respuestas() {
    }

	
    public Respuestas(Preguntas preguntas) {
        this.preguntas = preguntas;
    }
    public Respuestas(Preguntas preguntas, String respuesta, String respuestaExamen) {
       this.preguntas = preguntas;
       this.respuesta = respuesta;
       this.respuestaExamen = respuestaExamen;
    }
   
    public Integer getIdRespuesta() {
        return this.idRespuesta;
    }
    
    public void setIdRespuesta(Integer idRespuesta) {
        this.idRespuesta = idRespuesta;
    }
    public Preguntas getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Preguntas preguntas) {
        this.preguntas = preguntas;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public String getRespuestaExamen() {
        return this.respuestaExamen;
    }
    
    public void setRespuestaExamen(String respuestaExamen) {
        this.respuestaExamen = respuestaExamen;
    }




}


