package com.ipn.mx.model.entities;
// Generated 8/11/2016 12:07:37 AM by Hibernate Tools 4.3.1



/**
 * Respuestas generated by hbm2java
 */
public class Respuestas  implements java.io.Serializable {


     private Integer idRespuesta;
     private Preguntas preguntas;
     private String respuesta;

    public Respuestas() {
    }

	
    public Respuestas(Preguntas preguntas) {
        this.preguntas = preguntas;
    }
    public Respuestas(Preguntas preguntas, String respuesta) {
       this.preguntas = preguntas;
       this.respuesta = respuesta;
    }
   
    public Integer getIdRespuesta() {
        return this.idRespuesta;
    }
    
    public void setIdRespuesta(Integer idRespuesta) {
        this.idRespuesta = idRespuesta;
    }
    public Preguntas getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Preguntas preguntas) {
        this.preguntas = preguntas;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }




}


