package com.ipn.mx.model.entities;
// Generated 1/11/2016 06:37:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Long idRol;
     private String rol;
     private Set materiases = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Roles() {
    }

    public Roles(String rol, Set materiases, Set usuarios) {
       this.rol = rol;
       this.materiases = materiases;
       this.usuarios = usuarios;
    }
   
    public Long getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Long idRol) {
        this.idRol = idRol;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set getMateriases() {
        return this.materiases;
    }
    
    public void setMateriases(Set materiases) {
        this.materiases = materiases;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


