package com.ipn.mx.model.entities;
// Generated 1/11/2016 06:13:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private long idRol;
     private String rol;
     private Set<Materias> materiases = new HashSet<Materias>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Roles() {
    }

	
    public Roles(long idRol) {
        this.idRol = idRol;
    }
    public Roles(long idRol, String rol, Set<Materias> materiases, Set<Usuario> usuarios) {
       this.idRol = idRol;
       this.rol = rol;
       this.materiases = materiases;
       this.usuarios = usuarios;
    }
   
    public long getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(long idRol) {
        this.idRol = idRol;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set<Materias> getMateriases() {
        return this.materiases;
    }
    
    public void setMateriases(Set<Materias> materiases) {
        this.materiases = materiases;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


