package com.ipn.mx.model.entities;
// Generated 1/11/2016 06:13:01 PM by Hibernate Tools 4.3.1



/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private long idTipoUsuario;
     private Usuario usuario;
     private String tipo;

    public Tipousuario() {
    }

	
    public Tipousuario(long idTipoUsuario, Usuario usuario) {
        this.idTipoUsuario = idTipoUsuario;
        this.usuario = usuario;
    }
    public Tipousuario(long idTipoUsuario, Usuario usuario, String tipo) {
       this.idTipoUsuario = idTipoUsuario;
       this.usuario = usuario;
       this.tipo = tipo;
    }
   
    public long getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(long idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


