package com.ipn.mx.model.entities;
// Generated 2/11/2016 10:58:55 PM by Hibernate Tools 4.3.1



/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private Long idTipoUsuario;
     private Usuario usuario;
     private String tipo;

    public Tipousuario() {
    }

	
    public Tipousuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Tipousuario(Usuario usuario, String tipo) {
       this.usuario = usuario;
       this.tipo = tipo;
    }
   
    public Long getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(Long idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


