package com.ipn.mx.model.entities;
// Generated 13/12/2016 12:01:18 PM by Hibernate Tools 4.3.1



/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private Long idTipoUsuario;
     private Usuario usuario;
     private Integer tipo;

    public Tipousuario() {
    }

	
    public Tipousuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Tipousuario(Usuario usuario, Integer tipo) {
       this.usuario = usuario;
       this.tipo = tipo;
    }
   
    public Long getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(Long idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }




}


