package com.ipn.mx.model.entities;
// Generated 1/11/2016 06:37:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {
    
     private long matricula;
     private Carrera carrera;
     private Roles roles;
     private String nombreUsuario;
     private String paternoUsuario;
     private String maternoUsuario;
     private Date fechaNacimiento;
     private String calle;
     private String colonia;
     private Integer numero;
     private Long codigoPostal;
     private Character sexo;
     private String email;
     private String nipUsuario;
     private String claveUsuario;
     private Set calificacioneses = new HashSet(0);
     private Set tipousuarios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(long matricula) {
        this.matricula = matricula;
    }
    public Usuario(long matricula, Carrera carrera, Roles roles, String nombreUsuario, String paternoUsuario, String maternoUsuario, Date fechaNacimiento, String calle, String colonia, Integer numero, Long codigoPostal, Character sexo, String email, Set calificacioneses, Set tipousuarios) {
       this.matricula = matricula;
       this.carrera = carrera;
       this.roles = roles;
       this.nombreUsuario = nombreUsuario;
       this.paternoUsuario = paternoUsuario;
       this.maternoUsuario = maternoUsuario;
       this.fechaNacimiento = fechaNacimiento;
       this.calle = calle;
       this.colonia = colonia;
       this.numero = numero;
       this.codigoPostal = codigoPostal;
       this.sexo = sexo;
       this.email = email;
       this.calificacioneses = calificacioneses;
       this.tipousuarios = tipousuarios;
    }
   
    public long getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(long matricula) {
        this.matricula = matricula;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPaternoUsuario() {
        return this.paternoUsuario;
    }
    
    public void setPaternoUsuario(String paternoUsuario) {
        this.paternoUsuario = paternoUsuario;
    }
    public String getMaternoUsuario() {
        return this.maternoUsuario;
    }
    
    public void setMaternoUsuario(String maternoUsuario) {
        this.maternoUsuario = maternoUsuario;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Long getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(Long codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the nipUsuario
     */
    public String getNipUsuario() {
        return nipUsuario;
    }

    /**
     * @param nipUsuario the nipUsuario to set
     */
    public void setNipUsuario(String nipUsuario) {
        this.nipUsuario = nipUsuario;
    }

    /**
     * @return the claveUsuario
     */
    public String getClaveUsuario() {
        return claveUsuario;
    }

    /**
     * @param claveUsuario the claveUsuario to set
     */
    public void setClaveUsuario(String claveUsuario) {
        this.claveUsuario = claveUsuario;
    }
    public Set getCalificacioneses() {
        return this.calificacioneses;
    }
    
    public void setCalificacioneses(Set calificacioneses) {
        this.calificacioneses = calificacioneses;
    }
    public Set getTipousuarios() {
        return this.tipousuarios;
    }
    
    public void setTipousuarios(Set tipousuarios) {
        this.tipousuarios = tipousuarios;
    }




}


